### ISSUE TITLE
Contributors of a specific file

### ISSUE THREAD

**Issue by AndreyAkinshin** [blossom/contributors#3]
I want to display contributors of a specific file in a repo. How can I do it?

**Comment by nikgraf** [comment]
@AndreyAkinshin The current version doesn't support it. You could have a deeper look at the Github API. I had brief look & only found contributors for Repos: https://developer.github.com/v3/repos/collaborators/

**Comment by AndreyAkinshin** [comment]
http://stackoverflow.com/questions/13430769/getting-github-individual-file-contributors

**Comment by nikgraf** [comment]
Nice! Are you interested in working on it & creating a PR?

**Comment by AndreyAkinshin** [comment]
Unfortunately, right now I have no time.

**Comment by nikgraf** [comment]
@AndreyAkinshin too bad, but similar situation for me. I currently focus on other things.
